/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author 349041988
 */
public class MainFrameArea extends javax.swing.JFrame {

    /**
     * Creates new form MainFrameArea
     */
    public MainFrameArea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainDrawingArea1 = new MainDrawingArea();
        quit = new javax.swing.JButton();
        start = new javax.swing.JButton();
        pause = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 500));

        quit.setBackground(new java.awt.Color(0, 250, 0));
        quit.setText("Quit");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });

        start.setBackground(new java.awt.Color(0, 250, 0));
        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        pause.setBackground(new java.awt.Color(0, 255, 0));
        pause.setText("Pause");
        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainDrawingArea1Layout = new javax.swing.GroupLayout(mainDrawingArea1);
        mainDrawingArea1.setLayout(mainDrawingArea1Layout);
        mainDrawingArea1Layout.setHorizontalGroup(
            mainDrawingArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainDrawingArea1Layout.createSequentialGroup()
                .addContainerGap(414, Short.MAX_VALUE)
                .addGroup(mainDrawingArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainDrawingArea1Layout.createSequentialGroup()
                        .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(460, 460, 460)
                        .addComponent(quit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(466, 466, 466))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainDrawingArea1Layout.createSequentialGroup()
                        .addComponent(pause, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        mainDrawingArea1Layout.setVerticalGroup(
            mainDrawingArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainDrawingArea1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pause, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 531, Short.MAX_VALUE)
                .addGroup(mainDrawingArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(278, 278, 278))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainDrawingArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainDrawingArea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // When the game is started.
    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        disablePage();
    }//GEN-LAST:event_startActionPerformed

    // If quitting the game.
    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitActionPerformed

    // If pausing or unpausing game.
    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
        if (!MainDrawingArea.gamePause) {
            pausePage();
        } else if (MainDrawingArea.gamePause) {
            playPage();
        }
    }//GEN-LAST:event_pauseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrameArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrameArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrameArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrameArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrameArea().setVisible(true);
            }
        });
    }
    
    /** Turns on the starting page
     */
    public static void enablePage() {
        MainDrawingArea.gameOver = true;
        MainDrawingArea.gamePause = false;
        pause.setEnabled(false);
        pause.setVisible(false);
        start.setEnabled(true);
        quit.setEnabled(true);
        start.setVisible(true);
        quit.setVisible(true);
    }
    
    /** Turns off the starting page
     */
    public static void disablePage() {
        GameManager.setup();
        MainDrawingArea.gameOver = false;
        MainDrawingArea.gamePause = false;
        pause.setText("Pause");
        start.setText("Start");
        pause.setEnabled(true);
        pause.setVisible(true);
        start.setEnabled(false);
        quit.setEnabled(false);
        start.setVisible(false);
        quit.setVisible(false);
    }
    
    /** Turns on the pause page
     */
    public static void pausePage() {
        MainDrawingArea.gamePause = true;
        pause.setText("Play");
        start.setText("Restart");
        pause.setEnabled(true);
        pause.setVisible(true);
        start.setEnabled(true);
        quit.setEnabled(true);
        start.setVisible(true);
        quit.setVisible(true);
    }
    
    /** Turns off the pause page
     */
    public static void playPage() {
        MainDrawingArea.gamePause = false;
        pause.setText("Pause");
        start.setText("Start");
        pause.setEnabled(true);
        pause.setVisible(true);
        start.setEnabled(false);
        quit.setEnabled(false);
        start.setVisible(false);
        quit.setVisible(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private MainDrawingArea mainDrawingArea1;
    private static javax.swing.JButton pause;
    private static javax.swing.JButton quit;
    private static javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
